language: python
python:
 - "2.7"

install:
 - sudo apt-get update -qq 
 - sudo apt-get install python-dev xvfb
 - sudo apt-get install scrot libjpeg-dev zlib1g-dev xdotool eagle:i386 xserver-xephyr
 - sudo apt-get install libboost-thread-dev zlib1g-dev libpng12-dev libjpeg-turbo8-dev libtiff4-dev libopenexr-dev libsdl-gfx1.2-dev
 - pip install -r requirements-doc.txt

script:  
 - xauth add :0 . `mcookie`
 - paver cog html  


